package main

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/wangle201210/zskc/internal/original"
)

func main() {
	in := flag.String("in", "decoded/world0", "decoded world directory")
	out := flag.String("out", "docs/angkor-world0-inventory.md", "markdown output path")
	flag.Parse()

	pack, err := original.LoadWorldDir(*in)
	if err != nil {
		fatal(err)
	}
	doc := renderMarkdown(pack, *in)
	if err := os.WriteFile(*out, []byte(doc), 0o644); err != nil {
		fatal(err)
	}
	fmt.Printf("wrote %s for %d stages\n", *out, len(pack.Stages))
}

func renderMarkdown(pack *original.WorldPack, in string) string {
	var b strings.Builder
	b.WriteString("# Angkor World 0 Original Data Inventory\n\n")
	b.WriteString("Generated by `tools/drworldaudit` from decoded original stage JSON.\n\n")
	b.WriteString("This is an implementation checklist for rebuilding Diamond Rush World 0. Raw IDs are preserved until a Java runtime/source anchor proves their role.\n\n")
	b.WriteString("## Pack Summary\n\n")
	b.WriteString(fmt.Sprintf("- Source: `%s`\n", pack.Source))
	b.WriteString(fmt.Sprintf("- Decoded directory: `%s`\n", in))
	b.WriteString(fmt.Sprintf("- Stage count: `%d`\n", pack.StageCount))
	b.WriteString(fmt.Sprintf("- Tile size: `%dpx`\n", original.TileSize))
	b.WriteString(fmt.Sprintf("- Logical screen: `%dx%d`\n\n", original.ScreenWidth, original.ScreenHeight))

	b.WriteString("## Stage Summary\n\n")
	b.WriteString("| Stage | Size | Entrance marker | Known foreground anchors | Known player anchors |\n")
	b.WriteString("| ---: | ---: | --- | --- | --- |\n")
	for _, stage := range pack.Stages {
		b.WriteString(fmt.Sprintf("| %02d | %dx%d | %s | %s | %s |\n",
			stage.Index,
			stage.Width,
			stage.Height,
			formatPoints(stage.EntranceMarkers()),
			formatKnown(stage, original.ForegroundLayer),
			formatKnown(stage, original.PlayerLayer),
		))
	}

	b.WriteString("\n## World 0 Raw ID Coverage\n\n")
	for _, layer := range []original.Layer{original.PlayerLayer, original.ForegroundLayer, original.BackgroundLayer} {
		b.WriteString("### " + string(layer) + "\n\n")
		b.WriteString("| ID | Java signed | Count | Role |\n")
		b.WriteString("| ---: | ---: | ---: | --- |\n")
		for _, row := range aggregate(pack, layer) {
			role := "unclassified"
			if known, ok := original.KnownRole(layer, row.id); ok {
				role = known.Name + " (" + known.Confidence + ")"
			}
			b.WriteString(fmt.Sprintf("| %d | %d | %d | %s |\n", row.id, row.id.Signed(), row.count, role))
		}
		b.WriteString("\n")
	}

	b.WriteString("## Current Implementation Implications\n\n")
	b.WriteString("- Do not map raw stage IDs into a guessed tile enum; preserve the original layer values.\n")
	b.WriteString("- Runtime must keep three mutable layers: player/object, background/state, foreground.\n")
	b.WriteString("- Raw `255` must be treated like Java signed `-1`/empty.\n")
	b.WriteString("- Stage start is currently anchored by player-layer raw `79`; Java stage init handles it specially.\n")
	b.WriteString("- Foreground raw `0` is a one-shot foreground event; Java records the merged background/state in `bmInt` while the player stands on it, then clears the foreground cell.\n")
	b.WriteString("- Foreground raw `1` is a clearable foreground cluster; Java movement into raw `1` calls `bVoid(x,y,(byte)1)`, recursively clearing connected raw `1` cells.\n")
	b.WriteString("- Foreground raw `4` is checkpoint behavior; stepping on it activates/saves by background/state order, Action/5 restores, `*` on the checkpoint restores without cost, and `*` away from it recalls through the death-style life-cost path.\n")
	b.WriteString("- Player-layer raw `0` is a boulder; Java falling branches call `hurtHero(2, 48, 0)` when it crushes the player.\n")
	b.WriteString("- Player-layer raw `4` and `5` are key pickups; Java pickup branches increment `aUInt`/`aVInt`, and foreground raw `9`/`8` door branches consume them.\n")
	b.WriteString("- Foreground raw `2` is a passable current-cell special-item interaction; state `0` recursively clears when it no longer has adjacent player-layer raw `30` breakable walls, while state `1` shows the hook prompt and requires Action/5 with tool level `>=2`.\n")
	b.WriteString("- Foreground raw `6` is a pressure door switch; Java reads its background/state as a door index, calls `hVoid(doorI)` while pressed, and calls `doorHeadClose(doorI)` when released.\n")
	b.WriteString("- Foreground raw `7` is a stateful door; Java movement blocks it while the merged foreground high-state nibble is `< 2`, and decoded background/state `255` represents an already-open/passable door cell.\n")
	b.WriteString("- Foreground raw `8`/`9` are keyed locks; their cells use player-layer raw `31` as the lock body/animation carrier.\n")
	b.WriteString("- Foreground raw `17` is an enemy-gate group marker, not the player trigger. Java removes markers beneath grouped enemies during initialization, retains markers beneath linked doors/containers, and opens or unlocks those targets when the active group counter reaches zero.\n")
	b.WriteString("- Foreground raw `14`/`33` directly above a raw `17` group marker are locked reward containers; their payload stays hidden and inert until the matching enemy-gate counter reaches zero, then the overlay unlocks without replacing its authored background payload.\n")
	b.WriteString("- Foreground raw `26` is an enemy-gate trigger switch; Java activates `cmInt` from its background/state group while the player stands on it, then clears the raw `26` cell.\n")
	b.WriteString("- Player-layer raw `2` is a red diamond; Java dispatches it to `lVoid(2)`, uses pickup texture slot `3`, increments `bbInt`, and original text names this currency `Red diamonds`.\n")
	b.WriteString("- Player-layer raw `6` is an extra life pickup; Java pickup code increments `azInt`, the death branch decrements it, and checkpoint restore does not roll it back.\n")
	b.WriteString("- Player-layer raw `7` is a health refill pickup; Java pickup code calls `aVoid((byte)127)`, clamped to max health.\n")
	b.WriteString("- Player-layer raw `10` is diggable vegetation in Angkor: Java movement permits it while `xByte == 3`, marks its state active, then object update clears the player-layer cell and writes foreground raw `32` for the `aClassfArr[16]` removal animation.\n")
	b.WriteString("- Player-layer raw `11` is a crawling enemy; Java stage init seeds state from background raw `1`, the object update dispatches it to `amVoid()`, contact calls `hurtHero(1,64,0)`, and falling-object branches can clear it like other contact enemies.\n")
	b.WriteString("- Player-layer raw `12` is a visible blocking bonus-quota gate. Original-JAR runtime inspection retains it, stores its coordinate in `abInt/acInt` and background value in `aaInt`, draws `cm.f` chunk `5` plus the remaining number, and clears the cell only when raw `1`/`41` collection reduces the quota to zero. The apparent initialization clear in readable `i.java` is a decompiler artifact.\n")
	b.WriteString("- Player-layer raw `22`/`23` are horizontal hazards; Java render uses `aClassfArr[12]`, and the object update checks same-row player positions over animation reach before calling `hurtHero(1,64,0)`.\n")
	b.WriteString("- Player-layer raw `24`/`26`/`27` are source-special pickups handled through `mVoid()`, setting Java `iByteArr[9]` to `1`/`8`/`2` respectively; Action/5 hammer/local checks require level `>=1`, and hook scanning requires level `>=2`.\n")
	b.WriteString("- Player-layer raw `30` is a breakable wall; Java `dBoolean` excludes it, the tool branch starts/increments `bIntArrArr` damage state, propagates adjacent raw `30` at state `4`, and clears it at state `>=16`.\n")
	b.WriteString("- Player-layer raw `33` is a passable persistent marker; Java stage init preserves it and the movement helper groups it with passable IDs, but it has no player-object render branch. Foreground raw `33`, when present, owns the visible `aClassfArr[22]` overlay.\n")
	b.WriteString("- Player-layer raw `41` is a value-bearing violet-diamond pickup; Java adds its background value to both the stage violet total `aYInt` during initialization and collected violet count `aZInt` after the pickup animation.\n")
	b.WriteString("- Player-layer raw `42` is the Compass; Java `lVoid(42)` selects `textures[29][0]` from `gen3.f` chunk `1`, then sets `pBoolean` and starts tutorial script `11` through `bmInt=11`.\n")
	b.WriteString("- Player-layer raw `53` is a source-special artifact pickup; Java `lVoid(53)` enters pickup animation `32`, sets `DInt=0`, and stores bit `0` in `iByteArr[2]`.\n")
	b.WriteString("- Java `eBoolean` treats foreground raw `5` and `28` goal markers as non-empty for falling object movement.\n")
	b.WriteString("- Player-layer raw `19`/`43` are snakes; Java object update dispatches to `eVoid((byte)19/43)`, low state bits carry direction, player contact calls `hurtHero(1, 48, ...)`, and falling-object branches clear snakes when hit.\n")
	b.WriteString("- All 14 packed Angkor stages are loaded by the runtime. This inventory is a data audit; behavioral fidelity is established by the per-stage source-cadence regressions and the source mappings in `AGENTS.md`.\n")
	return b.String()
}

type idCount struct {
	id    original.RawID
	count int
}

func aggregate(pack *original.WorldPack, layer original.Layer) []idCount {
	counts := map[original.RawID]int{}
	for _, stage := range pack.Stages {
		for id, count := range stage.Histograms[layer] {
			counts[id] += count
		}
	}
	rows := make([]idCount, 0, len(counts))
	for id, count := range counts {
		rows = append(rows, idCount{id: id, count: count})
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].id < rows[j].id })
	return rows
}

func formatKnown(stage *original.Stage, layer original.Layer) string {
	var parts []string
	for _, id := range stage.UniqueIDs(layer) {
		role, ok := original.KnownRole(layer, id)
		if !ok || id == original.EmptyRawID {
			continue
		}
		count := stage.Histograms[layer][id]
		parts = append(parts, fmt.Sprintf("%d %s:%d", id, role.Name, count))
	}
	if len(parts) == 0 {
		return "-"
	}
	if len(parts) > 6 {
		parts = append(parts[:6], fmt.Sprintf("+%d more", len(parts)-6))
	}
	return strings.Join(parts, "<br>")
}

func formatPoints(points []original.Point) string {
	if len(points) == 0 {
		return "-"
	}
	out := make([]string, len(points))
	for i, pt := range points {
		out[i] = fmt.Sprintf("(%d,%d)", pt.X, pt.Y)
	}
	return strings.Join(out, ", ")
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "drworldaudit:", err)
	os.Exit(1)
}
